name: Docker Image Build
 
on:
  push:
    branches:
      - xeniya
  workflow_dispatch:
 

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ vars.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD_XF }}
  ACR_USERNAME: ${{ vars.ACR_USERNAME_XF }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
   
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
    - name: Build the Docker image
      uses: azure/docker-login@v1
      with:
        login-server: xeniya001.azurecr.io
        username: ${{ vars.ACR_USERNAME_XF }}
        password: ${{ secrets.ACR_PASSWORD_XF }}
    - run: |
        docker build . -t hello-world:${{ github.sha }}
        docker tag hello-world:${{ github.sha }} xeniya001.azurecr.io/hello-world:${{ github.sha }}
        docker push xeniya001.azurecr.io/hello-world:${{ github.sha }}
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
 
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
 
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: EIS_DEVTEST-INT-EAST-SANDBOX-RG
        dns-name-label: hello-world
        image: xeniya001.azurecr.io/hello-world:${{ github.sha }}
        cpu: 1
        memory: 1
        registry-login-server:  ${{ vars.ACR_SERVER_XF }}
        registry-username: ${{ vars.ACR_USERNAME_XF }}
        registry-password: ${{ secrets.ACR_PASSWORD_XF }}
        name: aci-aci-poc
        location: 'East US'
