name: Docker Image Build
 
on:
  push:
    branches:
      - xeniya
  workflow_dispatch:
 

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD_XF }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
   
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: Build the Docker image
      run: docker build -t xeniya001.azurecr.io/hello-world -t xeniya001.azurecr.io/hello-world:latest .
   
    - name: Push the Docker image
      run: docker push -a xeniya001.azurecr.io/hello-world:latest
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
 
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: EIS-DEVTEST-INT-EAST-SANDBOX-RG
        image: xeniya001.azurecr.io/hello-world:latest
        cpu: 2
        memory: 1
        registry-login-server:  ${{ vars.ACR_SERVER_XF }}
        registry-username: ${{ vars.ACR_USERNAME_XF }}
        registry-password: ${{ secrets.ACR_PASSWORD_XF }}
        name: acigroup-aci-poc
        location: 'us east'
